### ISSUE TITLE
Extending type of global `vim`

### ISSUE THREAD

**Issue by thenbe** [gkzhb/lua-types-nvim#1]
I was trying to add a few types for `vim.json` & `vim.loop`, but wasn't able to extend the type of global `vim` type. I've tried multiple ways (declaration merging, re-declaring global, etc), but the end result is always one of the following:

A. typescript compiler chooses my interface, and ignores the one from this library.
B. typescript compiler chooses the one from this library, and ignores mine.

There is some relevant [discussion](https://discord.com/channels/515854149821267971/515854150257344524/1072652182089908304) in the TSTL discord. One noteable [suggestion](https://discord.com/channels/515854149821267971/515854150257344524/1072658853881184346) as to the possible cause of this issue is that:

> declaration merging won't help because the interface IVim isn't global, it's scoped to the file where it's declared. The typings would need to declare it as global for it to work:

```ts
declare global {
  interface IVim {
    // ...
  }
}
```

**Comment by gkzhb** [comment]
Thanks for the advice. I've updated and you can try with v0.0.7.

**Comment by thenbe** [comment]
Thank you!
